// src/routes/play/components/question.svelte
<script lang="ts">
	import { Icon, CheckCircle, XCircle } from 'svelte-hero-icons';
	import { decodeHTMLEntities } from 'utils';
	import { playStore, questionStore } from 'store';
	import { Button } from 'components';
	import Transition from 'svelte-transition';
	import QuestionControls from './questionControls.svelte';
	import Timer from './timerCountdown.svelte';
	import { colorMap } from 'utils';
	import type { TQuestionAttributes } from 'models';
	import type { IconSource } from 'svelte-hero-icons';

	interface Props {
		index: number;
		question: TQuestionAttributes;
	}
	let { index, question: _question }: Props = $props();

	let answerFeedback: (IconSource | null)[] = $state([null, null, null, null]);

	const { answers: _answers, category, correctAnswer, difficulty, question, id } = _question;
	const answers = _answers.map((entity) => decodeHTMLEntities(entity));

	const updateUserStats = () => {
		const isEasy = difficulty === 'easy';
		const isMedium = difficulty === 'medium';
		const isHard = difficulty === 'hard';
		const answeredCorrect = questionStore.timers[index].userAnswer === correctAnswer;

		// create new stat entry
		if (!playStore.userStats[category]) {
			playStore.userStats[category] = {
				category,
				total: 1,
				totalCorrect: answeredCorrect ? 1 : 0,
				totalEasy: isEasy ? 1 : 0,
				totalEasyCorrect: isEasy && answeredCorrect ? 1 : 0,
				totalMedium: isMedium ? 1 : 0,
				totalMediumCorrect: isMedium && answeredCorrect ? 1 : 0,
				totalHard: isHard ? 1 : 0,
				totalHardCorrect: isHard && answeredCorrect ? 1 : 0
			};
		} else {
			// update existing entry
			const {
				totalCorrect,
				total,
				totalEasy,
				totalEasyCorrect,
				totalMedium,
				totalMediumCorrect,
				totalHard,
				totalHardCorrect,
				...categoryStat
			} = playStore.userStats[category];

			const updatedStat = {
				...categoryStat,
				total: total + 1,
				totalCorrect: totalCorrect + (answeredCorrect ? 1 : 0),
				totalEasy: totalEasy + (isEasy ? 1 : 0),
				totalEasyCorrect: totalEasyCorrect + (answeredCorrect && isEasy ? 1 : 0),
				totalMedium: totalMedium + (isMedium ? 1 : 0),
				totalMediumCorrect: totalMediumCorrect + (isMedium && answeredCorrect ? 1 : 0),
				totalHard: totalHard + (isHard ? 1 : 0),
				totalHardCorrect: totalHardCorrect + (isHard && answeredCorrect ? 1 : 0)
			};

			playStore.userStats[category] = updatedStat;
		}
	};

	const handleUserAnswer = (answer: string, answerIndex: number) => {
		questionStore.timers[index].userAnswer = answer;
		questionStore.timers[index].state = 'ended';
		updateUserStats();
		playStore.answeredQuestions.push(id);
		console.debug({ playStore, questionStore });

		if (answer === correctAnswer) playStore.totalCorrect++;

		// display icon based on correct answer
		answerFeedback = answerFeedback.map((_, j) => {
			if (answerIndex === j) {
				return answer === correctAnswer ? CheckCircle : XCircle;
			}

			return j === answers.indexOf(correctAnswer) ? CheckCircle : null;
		});

		// give user feedback on answer
		const el = document.getElementById(answer);

		el?.style.setProperty('--animate-duration', '1s');
		if (answer === correctAnswer) {
			const audio = document.getElementById('success') as HTMLAudioElement;
			audio.play();
			el?.classList.add('animate__tada');
		} else {
			const audio = document.getElementById('error') as HTMLAudioElement;
			audio.play();
			el?.classList.add('animate__shakeX');
		}
	};
</script>

<Transition
	show={playStore.questionIndex === index}
	enter="transform transition duration-[400ms] delay-500"
	enterFrom="opacity-0 rotate-[-120deg] scale-50"
	enterTo="opacity-100 rotate-0 scale-100"
	leave="transform duration-200 transition ease-in-out"
	leaveFrom="opacity-100 rotate-0 scale-100 "
	leaveTo="opacity-0 scale-95"
>
	<div
		class="col gap-4 rounded-lg border-2 p-4 dark:border-light"
		style="min-width: 320px; max-width: 580px;"
	>
		<div class="flex justify-between">
			<p>{category}</p>
			<p style={`color: ${colorMap[difficulty]}`}>{difficulty}</p>
		</div>

		<Timer {index} />

		<strong>{question}</strong>

		<section aria-label="Question answers" class="grid grid-cols-2 grid-rows-2 gap-4">
			{#each answers as answer, i}
				<Button
					parentStyles="self-center"
					class={[
						'animate__animated flex w-full items-center justify-center gap-2',
						questionStore.timers[index].state === 'ended' ? 'cursor-not-allowed' : ''
					]}
					onclick={() => handleUserAnswer(answer, i)}
					id={answer}
					disabled={questionStore.timers[index].state !== 'started'}
					primary={!questionStore.timers[index].userAnswer &&
						questionStore.timers[index].state === 'ended' &&
						answer === correctAnswer}
					data-testid={answer}
				>
					{#if answerFeedback[i]}
						<span
							data-testid={`feedback-${answer === correctAnswer ? 'correct' : 'incorrect'}-${i}`}
						>
							<Icon src={answerFeedback[i]} size="20" />
						</span>
					{/if}
					<p>{decodeHTMLEntities(answer)}</p>
				</Button>
			{/each}
		</section>

		<QuestionControls {index} />

		<audio id="success">
			<source src="/success.mp3" type="audio/mpeg" />
			Your browser does not support the audio element.
		</audio>
		<audio id="error">
			<source src="/error.mp3" type="audio/mpeg" />
			Your browser does not support the audio element.
		</audio>
	</div>
</Transition>

// app/components/question.tsx
"use client";
import { useUser } from "@clerk/nextjs";
import { ReactNode, Fragment, useState, useEffect, useRef } from "react";
import { Button, QuestionBox } from "./styledComponents";
import Timer from "./timerCountdown";
import { CheckCircleIcon, XCircleIcon } from "@heroicons/react/24/outline";
import { Transition } from "@headlessui/react";
import "animate.css";

export interface IQuestion {
  category: string;
  answers: Array<string>;
  correctAnswer: string;
  id: string;
  question: string;
  difficulty: string;
}

export interface IQuestionProps {
  questionObj: IQuestion;
  index: number;
  questionNumber: number;
  setIndex: Function;
  questionsLength: number;
  updateProgress: Function;
  submitProgress: Function;
}

export default function Question({
  questionObj: { category, answers, correctAnswer, question, difficulty },
  index,
  questionNumber,
  setIndex,
  questionsLength,
  updateProgress,
  submitProgress,
}: IQuestionProps) {
  const [answerFeedback, setAnswerFeedback] = useState<ReactNode[]>([
    <></>,
    <></>,
    <></>,
    <></>,
  ]);
  const [timesUp, setTimesUp] = useState(false);
  const [CTA, setCTA] = useState("Next Question");
  const [timerHasStarted, setTimerHasStarted] = useState(true);
  const { user, isLoaded, isSignedIn } = useUser();
  const [error, setError] = useState(null);
  const [_userAnswer, _setUserAnswer] = useState("");
  const userAnswer = useRef(_userAnswer);
  const setUserAnswer = (answer) => {
    userAnswer.current = answer;
    _setUserAnswer(answer);
  };

  function handleUserAnswer(value: string, i: number) {
    setUserAnswer(value);
    // display icon based on correct answer
    setAnswerFeedback((state) =>
      state.map((_, j) => {
        if (i === j) {
          return value === correctAnswer ? (
            <CheckCircleIcon width={30} />
          ) : (
            <XCircleIcon width={30} />
          );
        }

        return j === answers.indexOf(correctAnswer) ? (
          <CheckCircleIcon width={30} />
        ) : (
          <></>
        );
      })
    );
    updateProgress(
      { category, answers, correctAnswer, question, difficulty },
      value
    );

    // give user feedback on answer

    const el = document.getElementById(value);

    el?.style.setProperty("--animate-duration", "1s");
    if (value === correctAnswer) {
      const audio = document.getElementById("success") as HTMLAudioElement;
      audio.play();
      el?.classList.add("animate__tada");
    } else {
      const audio = document.getElementById("error") as HTMLAudioElement;
      audio.play();
      el?.classList.add("animate__shakeX");
    }

    handleTimesUp();
  }

  function handleTimesUp() {
    // display correct answer if user did not click any button
    if (!userAnswer.current) {
      // animate correct answer
      const el = document.getElementById(correctAnswer);
      el?.style.setProperty("--animate-duration", "1s");
      el?.classList.add("animate__rubberBand");

      updateProgress(
        { category, answers, correctAnswer, question, difficulty },
        ""
      );
    }

    setTimesUp(true);
    setTimerHasStarted(false);
  }

  async function handleNextQuestion() {
    if (CTA === "Submit Results") {
      if (isLoaded && isSignedIn) {
        const res = await submitProgress(user.id);
        if (res.message === "User stats updated successfully")
          window.location.href = "/users/" + user.id;
        else setError(res);
      } else window.location.href = "/sign-in";
    } else setIndex((index: number) => index + 1);
  }

  async function handleViewProgress() {
    if (isLoaded && isSignedIn) {
      const res = await submitProgress(user.id);
      if (res.message === "User stats updated successfully")
        window.location.href = "/users/" + user.id;
      else setError(res);
    } else {
      window.location.href = "/sign-in";
    }
  }

  useEffect(() => {
    setCTA(
      !(index % 5)
        ? "Continue Playing"
        : index === questionsLength
        ? "Submit Results"
        : "Next Question"
    );
  });

  const colorMap: { [key: string]: string } = {
    easy: "green",
    medium: "gold",
    hard: "red",
  };

  return (
    <Transition
      as={Fragment}
      show={questionNumber === index}
      enter="transform transition duration-[400ms]"
      enterFrom="opacity-0 rotate-[-120deg] scale-50"
      enterTo="opacity-100 rotate-0 scale-100"
      leave="transform duration-200 transition ease-in-out"
      leaveFrom="opacity-100 rotate-0 scale-100 "
      leaveTo="opacity-0 scale-95 "
    >
      <QuestionBox className="question flex flex-col gap-7 rounded-lg p-6">
        <div className="flex justify-between items-center">
          <h1 className="text-xl">{category}</h1>

          <p className="text-xl" style={{ color: colorMap[difficulty] }}>
            {difficulty}
          </p>
        </div>

        <h1 className="text-2xl">{decodeHTMLEntities(question)}</h1>

        <Timer
          handleTimesUp={handleTimesUp}
          timerHasStarted={timerHasStarted}
        />

        <div className="question_options grid grid-cols-2 grid-rows-2 gap-4">
          {answers.map((answer, i) => {
            return (
              <Button
                className="flex justify-center gap-2 items-center animate__animated"
                onClick={() => handleUserAnswer(answer, i)}
                key={answer}
                id={answer}
                disabled={timesUp}
                style={{ cursor: !timesUp ? "pointer" : "not-allowed" }}
                $primary={
                  !userAnswer.current && timesUp && answer === correctAnswer
                }
              >
                <span>{answerFeedback[i]}</span>
                <p>{answer}</p>
              </Button>
            );
          })}
        </div>

        {timesUp && (
          <>
            <Button onClick={handleNextQuestion} $primary={true}>
              {CTA}
            </Button>

            {CTA === "Continue Playing" && (
              <Button onClick={handleViewProgress} $primary={true}>
                View Progress
              </Button>
            )}
          </>
        )}
        {error && <div>{error}</div>}
        <audio id="success">
          <source src="/success.mp3" type="audio/mpeg" />
          Your browser does not support the audio element.
        </audio>
        <audio id="error">
          <source src="/error.mp3" type="audio/mpeg" />
          Your browser does not support the audio element.
        </audio>
      </QuestionBox>
    </Transition>
  );
}

function decodeHTMLEntities(text: string): string {
  const p = document.createElement("p");
  p.innerHTML = text;
  return p.innerText;
}
