// src/routes/components/navigation/desktop.svelte
<script lang="ts">
        import { globalStore } from 'store';
        import { createDisclosure } from "svelte-headlessui";
        import {
                Bars3,
                ChartBar,
                UserCircle,
                XMark,
                Icon,
        } from "svelte-hero-icons";
        import { navStyles, navigation } from ".";

        let { path } = $props();
</script>

<nav class="hidden items-center md:flex text-light bg-secondary px-2 w-full">
        <a class="hover:bg-gray-700 rounded-md mr-auto text-xl ml-1 px-3 py-2" href="/">Trivia Mania</a>

        <div class="flex px-2 gap-1">
                {#each navigation as item}
                        <a
                                data-testid={item.name}
                                href={item.href}
                                class={[
                                        item.href.split("?")[0] === path
                                                ? navStyles.active
                                                : navStyles.inActive[0],
                                        navStyles.inActive[1]
                                ]}
                                aria-current={item.href === path ? "page" : undefined}
                        >
                                <Icon src={item.icon} size="25" />
                                {item.name}
                        </a>
                {/each}

                <!-- User stats and User button -->
                {#if $globalStore.user}
                        <a
                                data-testid="your-stats-button"
                                href={`/stats`}
                                class={[
                                        `/stats` === path
                                                ? navStyles.active
                                                : navStyles.inActive[0],
                                        navStyles.inActive[1]
                                ]}
                                aria-current={`/stats` === path ? "page" : undefined}
                        >
                                <Icon src={ChartBar} size="25" />
                                Your Stats
                        </a>

                        <a
                                href={`/settings`}
                                class={[
                                        `/settings` === path
                                                ? navStyles.active
                                                : navStyles.inActive[0],
                                        navStyles.inActive[1],
                                        "-ml-2 px-1"
                                ]}
                                aria-current={`/settings` === path ? "page" : undefined}
                        >
                                <img class="size-8 rounded-full" src={$globalStore.user?.avatar} alt="User icon" />
                        </a>
                {/if}
        </div>
</nav>

// app/components/navigation/desktop.tsx
/* Render desktop navbar */
"use client";
import { SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { ChartBarIcon, UserCircleIcon } from "@heroicons/react/24/outline";
import { CircularProgress } from "@mui/material";
import { motion } from "framer-motion";
import Link from "next/link";
import { NavProps } from ".";

export function classNames(...classes: Array<string>) {
  return classes.filter(Boolean).join(" ");
}

export const navStyles = {
  active:
    "bg-accent text-dark flex gap-2 content-center items-center hover:border-light border-2 border-accent hover:text-light hover:bg-accent-200",
  inActive: [
    "hover:bg-accent-100 hover:text-secondary",
    "rounded-md px-3 py-2 text-sm font-medium flex gap-2 content-center items-center",
  ],
};

export default function DesktopNav({
  navigation,
  path,
  userStatus: { user, isOnline, isLoaded },
}: NavProps) {
  return (
    <div className="hidden md:block mx-auto w-full px-2 md:px-6 lg:px-8 bg-secondary text-light z-10 sticky top-0">
      <div className="relative flex h-16 items-center justify-between">
        <div className="flex flex-1 items-center justify-center md:items-stretch md:justify-start">
          <div className="flex flex-shrink-0 items-center">
            <Link className="hover:bg-gray-700 rounded-md px-3 py-1" href="/">
              <h1 className="text-white text-3xl">Trivia Mania</h1>
            </Link>
          </div>
        </div>

        {/* Desktop Navigation */}
        <div
          className="absolute inset-y-0 right-0 flex items-center pr-2 md:static md:inset-auto md:ml-6 md:pr-0"
          data-testid="desktop-nav-container"
        >
          <div className="hidden md:ml-6 md:block">
            <div className="flex space-x-4">
              {navigation.map((item) => (
                <Link
                  key={item.name}
                  href={item.href}
                  className={classNames(
                    item.href.split("?")[0] === path
                      ? navStyles.active
                      : navStyles.inActive[0],
                    navStyles.inActive[1]
                  )}
                  aria-current={item.href === path ? "page" : undefined}
                >
                  {item.icon}
                  {item.name}
                </Link>
              ))}

              {/* User stats and Clerk.js User button */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 1.5 }}
                className="flex gap-3"
              >
                {isLoaded ? (
                  <>
                    {user && isOnline && (
                      <Link
                        href={`/users/${user.id}`}
                        className={classNames(
                          `/users/${user.id}` === path
                            ? navStyles.active
                            : navStyles.inActive[0],
                          navStyles.inActive[1]
                        )}
                        aria-current={
                          `/users/${user.id}` === path ? "page" : undefined
                        }
                      >
                        <ChartBarIcon height={25} width={25} />
                        Your Stats
                      </Link>
                    )}

                    <div
                      className={classNames(
                        /signin|signup/.test(path)
                          ? navStyles.active
                          : navStyles.inActive[0],
                        navStyles.inActive[1]
                      )}
                    >
                      <SignedIn>
                        {/* Mount the UserButton component */}
                        <UserButton />
                      </SignedIn>
                      <SignedOut>
                        <UserCircleIcon height={25} width={25} />
                        {/* Signed out users get sign in button */}
                        <SignInButton />
                      </SignedOut>
                    </div>
                  </>
                ) : (
                  <CircularProgress color="secondary" />
                )}
              </motion.div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
