// app/components/navigation/index.tsx
"use client";
import { GlobalContext } from "@/app/store";
import User from "@/models/user";
import {
  HomeIcon,
  PuzzlePieceIcon,
  StarIcon,
} from "@heroicons/react/24/outline";
import { usePathname } from "next/navigation";
import { useContext } from "react";
import DesktopNav from "./desktop";
import MobileNav from "./mobile";

type TNavigation = {
  name: string;
  href: string;
  icon: JSX.Element;
}[];
export interface NavProps {
  navigation: TNavigation;
  path: string;
  userStatus: {
    user: User | null;
    isLoaded: boolean;
    isOnline: boolean;
  };
}

export default function Navigation() {
  const path = usePathname();
  const {
    userStatus,
    playFilters: { difficulty, categories },
  } = useContext(GlobalContext);

  const navigation = [
    { name: "Home", href: "/", icon: <HomeIcon height={25} width={25} /> },
    {
      name: "Play",
      href: `/game?difficulty=${difficulty}&categories=${categories}`,
      icon: <PuzzlePieceIcon height={25} width={25} />,
    },
    {
      name: "Score Board",
      href: "/scoreboard",
      icon: <StarIcon height={25} width={25} />,
    },
  ];

  return (
    <>
      {/* Desktop Navigation */}
      <DesktopNav
        {...{
          path,
          navigation,
          userStatus,
        }}
      />

      {/* Mobile Navigation */}
      <MobileNav {...{ path, navigation, userStatus }} />
    </>
  );
}

// src/routes/components/navigation/index.svelte
<script lang="ts">
        import { Home, PuzzlePiece, Star } from 'svelte-hero-icons';
        import { globalStore, questionStore } from 'store';
	import MobileNav from './mobile.svelte';
	import DesktopNav from './desktop.svelte';

        let navigation = $derived([
                { name: 'Home', href: '/', icon: Home },
                {
                        name: 'Play',
                        href: `/play?difficulty=${globalStore.difficulty}&categories=${globalStore.categories}`,
                        icon: PuzzlePiece
                },
                {
                        name: 'Score Board',
                        href: '/scoreboard',
                        icon: Star
                }
        ]);

        let questionStarted = $derived(questionStore.timers.some(s => s.state === 'started'));
        const disabledLink = $derived(questionStarted && "pointer-events-none opacity-50");
</script>

<MobileNav {questionStarted} {navigation} {disabledLink} />
<DesktopNav {navigation} {disabledLink} />
