// app/components/scoreboard.tsx
import User from "@/models/user";
import Image from "next/image";

export default function Board({ topTenUsers }: { topTenUsers: Array<User> }) {
  const colorMap: { [key: string]: string } = {
    easy: "green",
    medium: "gold",
    hard: "red",
  };

  return (
    <div className="bg-gray-200 p-4">
      <h1 className="text-2xl font-semibold mb-4">Top 10 Scoreboard</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {topTenUsers.map((user, index) => (
          <div
            key={user.id}
            className="bg-white p-4 rounded-lg shadow-md flex flex-col gap-3"
          >
            <div className="flex items-center">
              <div className="mr-4">
                <Image
                  src={user.avatar}
                  alt={`Avatar for ${user.username}`}
                  width={50}
                  height={50}
                  className="rounded-full"
                />
              </div>
              <div>
                <p className="text-xl font-semibold">
                  {index + 1}. {user.username}
                </p>
                <p className="text-gray-500">
                  Total Correct Answers: {user.stats.total.correctAnswered}
                </p>
              </div>
            </div>
            <div className="flex gap-2 flex-col">
              {Object.keys(user.stats).map((category, i) => {
                if (!["easy", "hard", "medium", "total"].includes(category)) {
                  return (
                    <div key={`${category}_${i}`} className="flex flex-col">
                      <h3 className="text-gray-700">{category} Correct Answers</h3>

                      <div className="flex gap-3">
                        {Object.keys(user.stats[category]).map((difficulty) => {
                          const capitalized = difficulty.split("");
                          capitalized[0] = capitalized[0].toUpperCase();
                          const capitalizedDifficulty = capitalized.join("");

                          return (
                            <div
                             key={`${difficulty}_${i}`}
                              className="flex gap-1"
                              style={{ color: colorMap[difficulty] }}
                            >
                              <h4>{capitalizedDifficulty}:</h4>
                              <p>
                                {
                                  user.stats[category][difficulty]
                                    .correctAnswered
                                }
                              </p>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  );
                }
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// src/routes/scoreboard/+page.svelte
<script lang="ts">
        import { colorMap } from 'utils';
	let { data } = $props();
</script>

<svelte:head>
	<title>Scoreboard</title>
	<meta name="description" content="View the stats of the top 10 players | Leaderboard" />
</svelte:head>

<div class="overflow-y-auto p-4" data-testid="scoreboard-container">
	<h1 class="mb-4 text-xl font-semibold">Top 10 Scoreboard</h1>
	{#if data.topTen.length > 0}
		<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
			{#each data.topTen as { userStats, user, categoryStats }, index}
				<div
					class="col max-h-72 gap-3 overflow-y-auto rounded-lg border border-dark p-4 shadow-xl dark:border-transparent dark:bg-accent-200 bg-gray-200"
					data-testid={`user-${index}-stat`}
				>
					<div class="flex items-center">
						<div class="mr-4">
							<img
								src={user.avatar}
								alt={`Avatar for ${user.username}`}
								width={50}
								height={50}
								class="rounded-full"
							/>
						</div>
						<div>
							<p class="text-lg md:text-base font-semibold">
								{index + 1}. {user.username}
							</p>
							<p class="text-gray-500 md:text-sm">
								Total Correct Answers: {userStats.totalCorrect}
							</p>
						</div>
					</div>
					<div class="flex flex-col gap-2">
						{#each categoryStats as categoryStat}
							<div class="col">
								<h3 class="font-semibold text-gray-700 dark:text-gray-600">
									{categoryStat.category} correct answers
								</h3>

                                                                <div class="ml-4 flex gap-1" style={`color: ${colorMap['easy']}`}>
									<h4>Easy:</h4>
									<p>{categoryStat['totalEasyCorrect']}</p>
								</div>
                                                                <div class="ml-4 flex gap-1" style={`color: ${colorMap['medium']}`}>
									<h4>Medium:</h4>
									<p>{categoryStat['totalMediumCorrect']}</p>
								</div>
                                                                <div class="ml-4 flex gap-1" style={`color: ${colorMap['hard']}`}>
									<h4>Hard:</h4>
									<p>{categoryStat['totalHardCorrect']}</p>
								</div>
							</div>
						{/each}
					</div>
				</div>
			{/each}
		</div>
	{:else}
		<h1 class="text-2xl">There are currently no top ten players</h1>
	{/if}
</div>
